version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ] # Do not add default "dependency" label

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels: [ ] # Do not add default "dependency" label
