using Qowaiv.Financial;
using System.Collections.ObjectModel;

namespace Qowaiv.Globalization;

internal readonly partial struct CountryToCurrency
{
    public static readonly ReadOnlyCollection<CountryToCurrency> All = new(
    [
        new(Country.AD, Currency.ADP),
        new(Country.AD, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.AE, Currency.AED),
        new(Country.AF, Currency.AFN),
        new(Country.AG, Currency.XCD),
        new(Country.AI, Currency.XCD),
        new(Country.AL, Currency.ALL),
        new(Country.AM, Currency.AMD),
        new(Country.ANHH, Currency.ANG),
        new(Country.AO, Currency.AOA),
        new(Country.AR, Currency.ARS),
        new(Country.AS, Currency.USD),
        new(Country.AT, Currency.ATS),
        new(Country.AT, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.AU, Currency.AUD),
        new(Country.AW, Currency.AWG),
        new(Country.AX, Currency.FIM),
        new(Country.AX, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.AZ, Currency.AZN),
        new(Country.BA, Currency.BAM),
        new(Country.BB, Currency.BBD),
        new(Country.BB, Currency.USD),
        new(Country.BD, Currency.BDT),
        new(Country.BE, Currency.BEF),
        new(Country.BE, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.BF, Currency.XOF),
        new(Country.BG, Currency.BGN),
        new(Country.BH, Currency.BHD),
        new(Country.BI, Currency.BIF),
        new(Country.BJ, Currency.XOF),
        new(Country.BL, Currency.FRF),
        new(Country.BL, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.BM, Currency.BMD),
        new(Country.BN, Currency.BND),
        new(Country.BO, Currency.BOB),
        new(Country.BQ, Currency.USD),
        new(Country.BR, Currency.BRL),
        new(Country.BS, Currency.BSD),
        new(Country.BT, Currency.BTN),
        new(Country.BUMM, Currency.MMK),
        new(Country.BV, Currency.NOK),
        new(Country.BW, Currency.BWP),
        new(Country.BY, Currency.BYR),
        new(Country.BZ, Currency.BZD),
        new(Country.CA, Currency.CAD),
        new(Country.CC, Currency.AUD),
        new(Country.CD, Currency.CDF),
        new(Country.CF, Currency.XAF),
        new(Country.CG, Currency.XAF),
        new(Country.CH, Currency.CHF),
        new(Country.CI, Currency.XOF),
        new(Country.CK, Currency.NZD),
        new(Country.CL, Currency.CLP),
        new(Country.CM, Currency.XAF),
        new(Country.CN, Currency.CNY),
        new(Country.CO, Currency.COP),
        new(Country.CR, Currency.CRC),
        new(Country.CSHH, Currency.CSK),
        new(Country.CSXX, Currency.CSD),
        new(Country.CU, Currency.CUC),
        new(Country.CU, Currency.CUP),
        new(Country.CV, Currency.CVE),
        new(Country.CW, Currency.ANG),
        new(Country.CX, Currency.AUD),
        new(Country.CY, Currency.CYP),
        new(Country.CY, Currency.EUR, new Date(2008, 01, 01)),
        new(Country.CZ, Currency.CZK),
        new(Country.DDDE, Currency.DDM),
        new(Country.DDDE, Currency.DEM, new Date(1990, 07, 01)),
        new(Country.DE, Currency.DEM),
        new(Country.DE, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.DJ, Currency.DJF),
        new(Country.DK, Currency.DKK),
        new(Country.DM, Currency.XCD),
        new(Country.DO, Currency.DOP),
        new(Country.DZ, Currency.DZD),
        new(Country.EC, Currency.ECS),
        new(Country.EC, Currency.USD, new Date(2000, 03, 13)),
        new(Country.EE, Currency.EEK),
        new(Country.EE, Currency.EUR, new Date(2011, 01, 01)),
        new(Country.EG, Currency.EGP),
        new(Country.EH, Currency.MAD),
        new(Country.ER, Currency.ERN),
        new(Country.ES, Currency.ESP),
        new(Country.ES, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.ET, Currency.ETB),
        new(Country.FI, Currency.FIM),
        new(Country.FI, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.FJ, Currency.FJD),
        new(Country.FK, Currency.FKP),
        new(Country.FM, Currency.USD),
        new(Country.FO, Currency.DKK),
        new(Country.FR, Currency.FRF),
        new(Country.FR, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.GA, Currency.XAF),
        new(Country.GB, Currency.GBP),
        new(Country.GD, Currency.XCD),
        new(Country.GE, Currency.GEL),
        new(Country.GF, Currency.FRF),
        new(Country.GF, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.GG, Currency.GBP),
        new(Country.GH, Currency.GHS),
        new(Country.GI, Currency.GIP),
        new(Country.GL, Currency.DKK),
        new(Country.GM, Currency.GMD),
        new(Country.GN, Currency.GNF),
        new(Country.GP, Currency.FRF),
        new(Country.GP, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.GQ, Currency.XAF),
        new(Country.GR, Currency.GRD),
        new(Country.GR, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.GS, Currency.GBP),
        new(Country.GT, Currency.GTQ),
        new(Country.GU, Currency.USD),
        new(Country.GW, Currency.XOF),
        new(Country.GY, Currency.GYD),
        new(Country.HK, Currency.HKD),
        new(Country.HM, Currency.AUD),
        new(Country.HN, Currency.HNL),
        new(Country.HR, Currency.HRK),
        new(Country.HT, Currency.HTG),
        new(Country.HT, Currency.USD),
        new(Country.HU, Currency.HUF),
        new(Country.ID, Currency.IDR),
        new(Country.IE, Currency.IEP),
        new(Country.IE, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.IL, Currency.ILS),
        new(Country.IM, Currency.GBP),
        new(Country.IN, Currency.INR),
        new(Country.IO, Currency.GBP),
        new(Country.IQ, Currency.IQD),
        new(Country.IR, Currency.IRR),
        new(Country.IS, Currency.ISK),
        new(Country.IT, Currency.ITL),
        new(Country.IT, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.JE, Currency.GBP),
        new(Country.JM, Currency.JMD),
        new(Country.JO, Currency.JOD),
        new(Country.JP, Currency.JPY),
        new(Country.KE, Currency.KES),
        new(Country.KG, Currency.KGS),
        new(Country.KH, Currency.KHR),
        new(Country.KI, Currency.AUD),
        new(Country.KM, Currency.KMF),
        new(Country.KN, Currency.XCD),
        new(Country.KP, Currency.KPW),
        new(Country.KR, Currency.KRW),
        new(Country.KW, Currency.KWD),
        new(Country.KY, Currency.KYD),
        new(Country.KZ, Currency.KZT),
        new(Country.LA, Currency.LAK),
        new(Country.LB, Currency.LBP),
        new(Country.LC, Currency.XCD),
        new(Country.LI, Currency.CHF),
        new(Country.LK, Currency.LKR),
        new(Country.LR, Currency.LRD),
        new(Country.LS, Currency.LSL),
        new(Country.LT, Currency.LTL),
        new(Country.LT, Currency.EUR, new Date(2015, 01, 01)),
        new(Country.LU, Currency.LUF),
        new(Country.LU, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.LV, Currency.LVL),
        new(Country.LV, Currency.EUR, new Date(2014, 01, 01)),
        new(Country.LY, Currency.LYD),
        new(Country.MA, Currency.MAD),
        new(Country.MC, Currency.MCF),
        new(Country.MC, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.MD, Currency.MDL),
        new(Country.ME, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.MF, Currency.EUR),
        new(Country.MG, Currency.MGA),
        new(Country.MH, Currency.USD),
        new(Country.MK, Currency.MKD),
        new(Country.ML, Currency.XOF),
        new(Country.MM, Currency.MMK),
        new(Country.MN, Currency.MNT),
        new(Country.MO, Currency.HKD),
        new(Country.MO, Currency.MOP),
        new(Country.MP, Currency.USD),
        new(Country.MQ, Currency.FRF),
        new(Country.MQ, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.MR, Currency.MRO),
        new(Country.MS, Currency.XCD),
        new(Country.MT, Currency.MTL),
        new(Country.MT, Currency.EUR, new Date(2008, 01, 01)),
        new(Country.MU, Currency.MUR),
        new(Country.MV, Currency.MVR),
        new(Country.MW, Currency.MWK),
        new(Country.MX, Currency.MXN),
        new(Country.MX, Currency.MXV),
        new(Country.MY, Currency.MYR),
        new(Country.MZ, Currency.MZN),
        new(Country.NA, Currency.NAD),
        new(Country.NC, Currency.XPF),
        new(Country.NE, Currency.XOF),
        new(Country.NF, Currency.AUD),
        new(Country.NG, Currency.NGN),
        new(Country.NI, Currency.NIO),
        new(Country.NL, Currency.NLG),
        new(Country.NL, Currency.NLG),
        new(Country.NL, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.NO, Currency.NOK),
        new(Country.NP, Currency.NPR),
        new(Country.NR, Currency.AUD),
        new(Country.NU, Currency.NZD),
        new(Country.NZ, Currency.NZD),
        new(Country.OM, Currency.OMR),
        new(Country.PA, Currency.PAB),
        new(Country.PA, Currency.USD),
        new(Country.PE, Currency.PEN),
        new(Country.PF, Currency.XPF),
        new(Country.PG, Currency.PGK),
        new(Country.PH, Currency.PHP),
        new(Country.PK, Currency.PKR),
        new(Country.PL, Currency.PLN),
        new(Country.PM, Currency.FRF),
        new(Country.PM, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.PN, Currency.NZD),
        new(Country.PR, Currency.USD),
        new(Country.PS, Currency.ILS),
        new(Country.PT, Currency.PTE),
        new(Country.PT, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.PW, Currency.USD),
        new(Country.PY, Currency.PYG),
        new(Country.QA, Currency.QAR),
        new(Country.RE, Currency.FRF),
        new(Country.RE, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.RO, Currency.RON),
        new(Country.RS, Currency.RSD),
        new(Country.RU, Currency.RUB),
        new(Country.RW, Currency.RWF),
        new(Country.SA, Currency.SAR),
        new(Country.SB, Currency.SBD),
        new(Country.SC, Currency.SCR),
        new(Country.SD, Currency.SDG),
        new(Country.SE, Currency.SEK),
        new(Country.SG, Currency.SGD),
        new(Country.SH, Currency.GBP),
        new(Country.SH, Currency.SHP),
        new(Country.SI, Currency.SIT),
        new(Country.SI, Currency.EUR, new Date(2007, 01, 01)),
        new(Country.SJ, Currency.NOK),
        new(Country.SK, Currency.SKK),
        new(Country.SK, Currency.EUR, new Date(2009, 01, 01)),
        new(Country.SL, Currency.SLL),
        new(Country.SM, Currency.SML),
        new(Country.SM, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.SN, Currency.XOF),
        new(Country.SO, Currency.SOS),
        new(Country.SR, Currency.SRD),
        new(Country.SS, Currency.SSP),
        new(Country.ST, Currency.STD),
        new(Country.SUHH, Currency.SUR),
        new(Country.SV, Currency.USD),
        new(Country.SX, Currency.ANG),
        new(Country.SY, Currency.SYP),
        new(Country.SZ, Currency.SZL),
        new(Country.TC, Currency.USD),
        new(Country.TD, Currency.XAF),
        new(Country.TF, Currency.FRF),
        new(Country.TF, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.TG, Currency.XOF),
        new(Country.TH, Currency.THB),
        new(Country.TJ, Currency.TJS),
        new(Country.TK, Currency.NZD),
        new(Country.TL, Currency.USD),
        new(Country.TM, Currency.TMT),
        new(Country.TN, Currency.TND),
        new(Country.TO, Currency.TOP),
        new(Country.TR, Currency.TRY),
        new(Country.TT, Currency.TTD),
        new(Country.TV, Currency.AUD),
        new(Country.TW, Currency.TWD),
        new(Country.TZ, Currency.TZS),
        new(Country.UA, Currency.UAH),
        new(Country.UG, Currency.UGX),
        new(Country.UM, Currency.USD),
        new(Country.US, Currency.USD),
        new(Country.UY, Currency.UYU),
        new(Country.UZ, Currency.UZS),
        new(Country.VA, Currency.VAL),
        new(Country.VA, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.VC, Currency.XCD),
        new(Country.VE, Currency.VEF),
        new(Country.VG, Currency.USD),
        new(Country.VI, Currency.USD),
        new(Country.VN, Currency.VND),
        new(Country.VU, Currency.VUV),
        new(Country.WF, Currency.XPF),
        new(Country.WS, Currency.WST),
        new(Country.XK, Currency.EUR, new Date(2008, 02, 01)),
        new(Country.YE, Currency.YER),
        new(Country.YT, Currency.FRF),
        new(Country.YT, Currency.EUR, new Date(2002, 01, 01)),
        new(Country.YUCS, Currency.YUD, new Date(1961, 12, 31)),
        new(Country.YUCS, Currency.YUN, new Date(1985, 12, 31)),
        new(Country.YUCS, Currency.YUR, new Date(1988, 06, 30)),
        new(Country.YUCS, Currency.YOU, new Date(1989, 09, 30)),
        new(Country.YUCS, Currency.YUG, new Date(1989, 12, 31)),
        new(Country.YUCS, Currency.YUM, new Date(1990, 01, 23)),
        new(Country.ZA, Currency.ZAR),
        new(Country.ZM, Currency.ZMW),
        new(Country.ZRCD, Currency.ZRZ),
        new(Country.ZRCD, Currency.ZRN, new Date(1993, 01, 01)),
        new(Country.ZW, Currency.ZWC, new Date(1966, 02, 16)),
        new(Country.ZW, Currency.ZWD, new Date(1976, 04, 17)),
        new(Country.ZW, Currency.ZWN, new Date(2002, 07, 31)),
        new(Country.ZW, Currency.ZWR, new Date(2004, 07, 31)),
        new(Country.ZW, Currency.ZWL, new Date(2005, 02, 02)),
        new(Country.ZW, Currency.USD, new Date(2009, 04, 12)),
        new(Country.HVBF, Currency.XOF),
        new(Country.BQAQ, Currency.GBP),
    ]);
}
