//<auto-generated/>
using Qowaiv.Globalization;

namespace Qowaiv.Financial;

[DebuggerDisplay("Pattern = {Pattern,nq}, Curr = {Currency}, Generic = {IsGeneric}, Country = {Country,nq}")]
internal readonly record struct Bban(Country Country, ushort[] Pattern, bool Currency = false, bool IsGeneric = false)
{
    public Bban(string country, ushort[] pattern, bool currency = false, bool isGeneric = false) : this(Country.Parse(country), pattern, currency, isGeneric) { }

    private const ushort _0 = 1 << 0;
    private const ushort _1 = 1 << 1;
    private const ushort _2 = 1 << 2;
    private const ushort _3 = 1 << 3;
    private const ushort _4 = 1 << 4;
    private const ushort _5 = 1 << 5;
    private const ushort _6 = 1 << 6;
    private const ushort _7 = 1 << 7;
    private const ushort _8 = 1 << 8;
    private const ushort _9 = 1 << 9;
    private const ushort a = 1 << 10;
    private const ushort c = 1 << 11;
    private const ushort n = 1 << 12;

#pragma warning disable

    private static Bban gen(string country) => new(Country.Parse(country), [0,0,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c], IsGeneric: true);

    public static readonly Bban[] All =
    [
        default,
        default,
        default,
        new("AD", [0,0,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c]), //                      AD: 8n,12c
        new("AE", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        AE: 19n
        gen("AF"),
        gen("AG"),
        default,
        gen("AI"),
        default,
        default,
        new("AL", [0,0,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              AL: 8n,16c
        gen("AM"),
        default,
        new("AO", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    AO: 21n
        default,
        gen("AQ"),
        gen("AR"),
        gen("AS"),
        new("AT", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              AT: 16n
        gen("AU"),
        default,
        gen("AW"),
        gen("AX"),
        default,
        new("AZ", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              AZ: 4a,20c
        new("BA", [0,0,_3,_9,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                            BA: 16n
        gen("BB"),
        default,
        gen("BD"),
        new("BE", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                      BE: 12n
        new("BF", [0,0,n,n,c,c,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              BF: 2c,22n
        new("BG", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,c,c,c,c,c,c,c,c]), //                          BG: 4a,6n,8c
        new("BH", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                          BH: 4a,14c
        new("BI", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                BI: 23n
        new("BJ", [0,0,n,n,c,c,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              BJ: 2c,22n
        default,
        gen("BL"),
        gen("BM"),
        gen("BN"),
        gen("BO"),
        default,
        gen("BQ"),
        new("BR", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,a,c]), //            BR: 23n,1a,1c
        gen("BS"),
        gen("BT"),
        default,
        gen("BV"),
        gen("BW"),
        default,
        new("BY", [0,0,n,n,c,c,c,c,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              BY: 4c,4n,16c
        gen("BZ"),
        gen("CA"),
        default,
        gen("CC"),
        gen("CD"),
        default,
        new("CF", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                CF: 23n
        new("CG", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                CG: 23n
        new("CH", [0,0,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c]), //                            CH: 5n,12c
        new("CI", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              CI: 2a,22n
        default,
        gen("CK"),
        gen("CL"),
        new("CM", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                CM: 23n
        gen("CN"),
        gen("CO"),
        default,
        default,
        new("CR", [0,0,n,n,_0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                         CR: [0],17n
        default,
        default,
        gen("CU"),
        new("CV", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    CV: 21n
        gen("CW"),
        gen("CX"),
        new("CY", [0,0,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              CY: 8n,16c
        new("CZ", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      CZ: 20n
        default,
        default,
        default,
        default,
        new("DE", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                          DE: 18n
        default,
        default,
        default,
        default,
        new("DJ", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                DJ: 23n
        new("DK", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  DK: 14n
        default,
        gen("DM"),
        default,
        new("DO", [0,0,n,n,c,c,c,c,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              DO: 4c,20n
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("DZ", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                  DZ: 22n
        default,
        default,
        gen("EC"),
        default,
        new("EE", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              EE: 16n
        default,
        new("EG", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //            EG: 25n
        gen("EH"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("ER"),
        new("ES", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      ES: 20n
        gen("ET"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("FI", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  FI: 14n
        gen("FJ"),
        new("FK", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  FK: 2a,12n
        default,
        gen("FM"),
        default,
        new("FO", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  FO: 14n
        default,
        default,
        new("FR", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,n,n]), //                FR: 10n,11c,2n
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("GA", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                GA: 23n
        new("GB", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                          GB: 4a,14n
        default,
        gen("GD"),
        new("GE", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                          GE: 2a,16n
        gen("GF"),
        gen("GG"),
        gen("GH"),
        new("GI", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                        GI: 4a,15c
        default,
        default,
        new("GL", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  GL: 14n
        gen("GM"),
        gen("GN"),
        default,
        gen("GP"),
        new("GQ", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                GQ: 23n
        new("GR", [0,0,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                GR: 7n,16c
        gen("GS"),
        new("GT", [0,0,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              GT: 24c
        gen("GU"),
        default,
        new("GW", [0,0,n,n,c,c,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    GW: 2c,19n
        default,
        gen("GY"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("HK"),
        default,
        gen("HM"),
        new("HN", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              HN: 4a,20n
        default,
        default,
        default,
        new("HR", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                            HR: 17n
        default,
        gen("HT"),
        new("HU", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              HU: 24n
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("ID"),
        new("IE", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                          IE: 4a,14n
        default,
        default,
        default,
        default,
        default,
        default,
        new("IL", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        IL: 19n
        gen("IM"),
        gen("IN"),
        gen("IO"),
        default,
        new("IQ", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        IQ: 4a,15n
        new("IR", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                  IR: 22n
        new("IS", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                  IS: 22n
        new("IT", [0,0,n,n,a,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c]), //                IT: 1a,10n,12c
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("JE"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("JM"),
        default,
        new("JO", [0,0,n,n,a,a,a,a,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //          JO: 4a,4n,18c
        gen("JP"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("KE"),
        default,
        gen("KG"),
        gen("KH"),
        gen("KI"),
        default,
        default,
        default,
        new("KM", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                KM: 23n
        gen("KN"),
        default,
        gen("KP"),
        default,
        gen("KR"),
        default,
        default,
        default,
        default,
        new("KW", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //          KW: 4a,22c
        default,
        gen("KY"),
        new("KZ", [0,0,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                              KZ: 3n,13c
        gen("LA"),
        new("LB", [0,0,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //              LB: 4n,20c
        new("LC", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //      LC: 4a,24c
        default,
        default,
        default,
        default,
        default,
        new("LI", [0,0,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c]), //                            LI: 5n,12c
        default,
        gen("LK"),
        default,
        default,
        default,
        default,
        default,
        default,
        gen("LR"),
        gen("LS"),
        new("LT", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              LT: 16n
        new("LU", [0,0,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                              LU: 3n,13c
        new("LV", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                            LV: 4a,13c
        default,
        default,
        new("LY", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    LY: 21n
        default,
        new("MA", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              MA: 24n
        default,
        new("MC", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,n,n]), //                MC: 10n,11c,2n
        new("MD", [0,0,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                      MD: 20c
        new("ME", [0,0,_2,_5,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        ME: 18n
        gen("MF"),
        new("MG", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                MG: 23n
        gen("MH"),
        default,
        default,
        new("MK", [0,0,_0,_7,n,n,n,c,c,c,c,c,c,c,c,c,c,n,n]), //                              MK: 3n,10c,2n
        new("ML", [0,0,n,n,c,c,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              ML: 2c,22n
        gen("MM"),
        new("MN", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              MN: 4n,12n
        gen("MO"),
        gen("MP"),
        gen("MQ"),
        new("MR", [0,0,_1,_3,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              MR: 23n
        gen("MS"),
        new("MT", [0,0,n,n,a,a,a,a,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //        MT: 4a,5n,18c
        new("MU", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,_0,_0,_0,a,a,a], true), // MU: 4a,16n,[000],3a
        gen("MV"),
        gen("MW"),
        gen("MX"),
        gen("MY"),
        new("MZ", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    MZ: 21n
        gen("NA"),
        default,
        gen("NC"),
        default,
        new("NE", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              NE: 2a,22n
        gen("NF"),
        gen("NG"),
        default,
        new("NI", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              NI: 4a,20n
        default,
        default,
        new("NL", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n]), //                                  NL: 4a,10n
        default,
        default,
        new("NO", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                        NO: 11n
        gen("NP"),
        default,
        gen("NR"),
        default,
        default,
        gen("NU"),
        default,
        default,
        default,
        default,
        gen("NZ"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("OM", [0,0,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                        OM: 3n,16c
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("PA"),
        default,
        default,
        default,
        gen("PE"),
        gen("PF"),
        gen("PG"),
        gen("PH"),
        default,
        default,
        new("PK", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                      PK: 4a,16c
        new("PL", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              PL: 24n
        gen("PM"),
        gen("PN"),
        default,
        default,
        default,
        gen("PR"),
        new("PS", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //            PS: 4a,21c
        new("PT", [0,0,_5,_0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                  PT: 21n
        default,
        default,
        gen("PW"),
        default,
        gen("PY"),
        default,
        new("QA", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //            QA: 4a,21c
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("RE"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("RO", [0,0,n,n,a,a,a,a,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                      RO: 4a,16c
        default,
        default,
        default,
        new("RS", [0,0,_3,_5,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        RS: 18n
        default,
        new("RU", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //    RU: 14n,15c
        default,
        gen("RW"),
        default,
        default,
        default,
        new("SA", [0,0,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                      SA: 2n,18c
        gen("SB"),
        new("SC", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,a,a,a], true), //  SC: 4a,20n,3a
        new("SD", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                                  SD: 14n
        new("SE", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      SE: 20n
        default,
        gen("SG"),
        gen("SH"),
        new("SI", [0,0,_5,_6,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              SI: 15n
        gen("SJ"),
        new("SK", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      SK: 20n
        gen("SL"),
        new("SM", [0,0,n,n,a,n,n,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c]), //                SM: 1a,10n,12c
        new("SN", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              SN: 2a,22n
        new("SO", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                        SO: 19n
        default,
        default,
        gen("SR"),
        gen("SS"),
        new("ST", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    ST: 21n
        default,
        new("SV", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              SV: 4a,20n
        default,
        gen("SX"),
        gen("SY"),
        gen("SZ"),
        default,
        default,
        gen("TC"),
        new("TD", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                TD: 23n
        default,
        gen("TF"),
        new("TG", [0,0,n,n,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //              TG: 2a,22n
        gen("TH"),
        default,
        gen("TJ"),
        gen("TK"),
        new("TL", [0,0,_3,_8,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      TL: 19n
        gen("TM"),
        new("TN", [0,0,_5,_9,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                    TN: 20n
        gen("TO"),
        default,
        default,
        new("TR", [0,0,n,n,n,n,n,n,n,_0,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //                 TR: 5n,[0],16c
        default,
        gen("TT"),
        default,
        gen("TV"),
        gen("TW"),
        default,
        default,
        gen("TZ"),
        new("UA", [0,0,n,n,n,n,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //            UA: 6n,19c
        default,
        default,
        default,
        default,
        default,
        gen("UG"),
        default,
        default,
        default,
        default,
        default,
        gen("UM"),
        default,
        default,
        default,
        default,
        default,
        gen("US"),
        default,
        default,
        default,
        default,
        default,
        gen("UY"),
        gen("UZ"),
        new("VA", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                          VA: 18n
        default,
        gen("VC"),
        default,
        gen("VE"),
        default,
        new("VG", [0,0,n,n,a,a,a,a,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                      VG: 4a,16n
        default,
        gen("VI"),
        default,
        default,
        default,
        default,
        gen("VN"),
        default,
        default,
        default,
        default,
        default,
        default,
        gen("VU"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("WF"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("WS"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("XK", [0,0,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n]), //                              XK: 16n
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        new("YE", [0,0,n,n,a,a,a,a,n,n,n,n,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c]), //          YE: 4a,4n,18c
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("YT"),
        default,
        default,
        default,
        default,
        default,
        default,
        gen("ZA"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("ZM"),
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        default,
        gen("ZW"),
        default,
        default,
        gen("ZZ"),
    ];
}
