//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qowaiv.DomainModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QowaivDomainModelMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QowaivDomainModelMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qowaiv.DomainModel.QowaivDomainModelMessages", typeof(QowaivDomainModelMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version ({0}) of the event is not successive to the current version ({1})..
        /// </summary>
        public static string ArgumenException_VersionNotSuccessive {
            get {
                return ResourceManager.GetString("ArgumenException_VersionNotSuccessive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of the event does not match the identifier of the aggregate root..
        /// </summary>
        public static string ArgumentException_InvalidEventId {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The events belong to multiple aggregate roots..
        /// </summary>
        public static string ArgumentException_MultipleAggregates {
            get {
                return ResourceManager.GetString("ArgumentException_MultipleAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} does not exist for the aggregate root ({1})..
        /// </summary>
        public static string ArgumentOutOfRangeException_InvalidVersion {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The events are out of order as ther versions are not successive..
        /// </summary>
        public static string EventsOutOfOrderException {
            get {
                return ResourceManager.GetString("EventsOutOfOrderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided event stream does not contain a (potential) full history for an aggregate..
        /// </summary>
        public static string EventStreamNoFullHistoryException {
            get {
                return ResourceManager.GetString("EventStreamNoFullHistoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event of the type {0} is not supported for {1}..
        /// </summary>
        public static string EventTypeNotSupportedException {
            get {
                return ResourceManager.GetString("EventTypeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is immutable and can not be changed..
        /// </summary>
        public static string ImmutableAttribute_ErrorMessage {
            get {
                return ResourceManager.GetString("ImmutableAttribute_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change tracker has already been initialized..
        /// </summary>
        public static string InvalidOperationException_ChangeTrackerAlreadyInitialized {
            get {
                return ResourceManager.GetString("InvalidOperationException_ChangeTrackerAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The change tracker has not been initialized..
        /// </summary>
        public static string InvalidOperationException_ChangeTrackerNotInitialized {
            get {
                return ResourceManager.GetString("InvalidOperationException_ChangeTrackerNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event stream has already been initialized..
        /// </summary>
        public static string InvalidOperationException_InitializedEventStream {
            get {
                return ResourceManager.GetString("InvalidOperationException_InitializedEventStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities that are transient can not be stored in a hash table..
        /// </summary>
        public static string NotSupported_GetHashCodeOnIsTransient {
            get {
                return ResourceManager.GetString("NotSupported_GetHashCodeOnIsTransient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier of an entity can not be updated once it is set..
        /// </summary>
        public static string Validation_UpdateEntityId {
            get {
                return ResourceManager.GetString("Validation_UpdateEntityId", resourceCulture);
            }
        }
    }
}
