// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts.OpenApi
{
    /// <summary>Specifies the involved sub schema's of which at least one should be picked.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class AnyOfAttribute : global::Qowaiv.Diagnostics.Contracts.OpenApi.SubSchemasAttribute
    {
        public AnyOfAttribute(params string[] schemas) : base(schemas) { }
    }
}
