// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts.OpenApi
{
    /// <summary>Specifies the involved sub schema's.</summary>
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal abstract class SubSchemasAttribute : global::System.Attribute
    {
        protected SubSchemasAttribute(params string[] schemas) => Schemas = schemas;

        /// <summary>The specified sub schema's.</summary>
        public string[] Schemas { get; }
    }
}
