global using FluentAssertions;
global using NUnit.Framework;
global using Qowaiv;
global using Qowaiv.Diagnostics.Contracts;
global using Qowaiv.Financial;
global using Qowaiv.Formatting;
global using Qowaiv.Globalization;
global using Qowaiv.Hashing;
global using Qowaiv.Identifiers;
global using Qowaiv.IO;
global using Qowaiv.Json;
global using Qowaiv.Mathematics;
global using Qowaiv.Security;
global using Qowaiv.Security.Cryptography;
global using Qowaiv.Specs;
global using Qowaiv.Sql;
global using Qowaiv.Statistics;
global using Qowaiv.TestTools;
global using Qowaiv.TestTools.Globalization;
global using Qowaiv.Text;
global using Qowaiv.Web;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.Contracts;
global using System.Globalization;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Xml.Serialization;
global using CustomGuid = Qowaiv.Identifiers.Id<Qowaiv.Specs.ForGuid>;
global using Int32Id = Qowaiv.Identifiers.Id<Qowaiv.Specs.ForInt32>;
global using Int64Id = Qowaiv.Identifiers.Id<Qowaiv.Specs.ForInt64>;
global using StringId = Qowaiv.Identifiers.Id<Qowaiv.Specs.ForString>;
global using CustomUuid = Qowaiv.Identifiers.Id<Qowaiv.Specs.ForUuid>;
