#if NET8_0_OR_GREATER
#if DEBUG

using Qowaiv.TestTools.Resx;
using Qowaiv.TestTools.Wikipedia;

namespace Globalization.Countries_specs;

public class Constants
{
    [Test]
    public void Generates()
    {
        var all = Country.All.OrderBy(c => c.Name.Length).ThenBy(c => c.Name).ToArray();

        using var w = new StreamWriter(Solution.Root.File("src/Qowaiv/Generated/Globalization/Country.consts.generated.cs").FullName);
        
        w.WriteLine(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------");
        w.WriteLine();
        w.WriteLine("namespace Qowaiv.Globalization;");
        w.WriteLine();
        w.WriteLine("public readonly partial struct Country");
        w.WriteLine("{");

        foreach (var country in all)
        {
            if (country != all[0]) w.WriteLine();

            w.WriteLine($"    /// <summary>Describes the country {country.EnglishName} ({country.Name}).</summary>");
            if (country.EndDate is { } enddate)
            {
                w.WriteLine($"    /// <remarks>End date is {enddate:yyyy-MM-dd}.</remarks>");
            }
            w.WriteLine($"    public static readonly Country {country.Name} = new(\"{country.Name}\");");
        }
        w.WriteLine("}");


        w.Invoking(w => w.Flush()).Should().NotThrow();
    }
}

/// <remarks>
/// As fetching data from Wikipedia is time consuming (no benefits from caching)
/// and therefor not executed on a RELEASE build.
/// </remarks>
public class Resource_files
{
    internal static readonly IReadOnlyCollection<Iso3166_1> Iso3166_1s = new WikiLemma("ISO 3166-1", TestCultures.En).Transform(Iso3166_1.Parse).Result;
    internal static readonly IReadOnlyCollection<Iso3166_3> Iso3166_3s = new WikiLemma("ISO_3166-3", TestCultures.En).Transform(Iso3166_3.Parse).Result;

    [TestCaseSource(nameof(Iso3166_1s))]
    public void exsiting_reflect_info_of_Wikipedia(Iso3166_1 info)
    {
        var country = Country.Parse(info.A2);
        var summary = new Iso3166_1(country.EnglishName, country.IsoAlpha2Code, country.IsoAlpha3Code, country.IsoNumericCode);
        summary.Should().Be(info);
    }

    [TestCaseSource(nameof(Iso3166_3s))]
    public void former_reflect_info_of_Wikipedia(Iso3166_3 info)
    {
        var country = Country.Parse(info.Name);
        var summary = new Iso3166_3(
            country.EnglishName, 
            country.IsoAlpha2Code,
            country.IsoAlpha3Code,
            country.IsoNumericCode,
            country.StartDate.Year,
            country.EndDate.GetValueOrDefault().Year - 1,
            country.Name);

        summary.Should().Be(info);
    }

    public class Display_names
    {
        private static readonly IReadOnlyCollection<Country> Existing = Country.GetExisting().ToArray();

        [TestCaseSource(nameof(Existing))]
        public async Task match_nl_Wikipedia(Country country)
        {
            var lemma = new WikiLemma($"Sjabloon:{country.IsoAlpha2Code}", TestCultures.Nl);
            var display = await lemma.Transform(DisplayName.FromNL);
            display.Should().Be(country.GetDisplayName(TestCultures.Nl_NL));
        }

        [TestCaseSource(nameof(Existing))]
        public async Task match_de_Wikipedia(Country country)
        {
            try
            {
                var lemma = new WikiLemma($"Vorlage:{country.IsoAlpha3Code}", TestCultures.De);
                var display = await lemma.Transform(DisplayName.FromDE);
                display.Should().Be(country.GetDisplayName(TestCultures.De_DE));
            }
            catch (UnknownLemma) { /* Some do not follow this pattern. */ }
        }
    }

    public class Generates
    {
        [Test]
        public void neutral_culture()
        {
            var unknown = new CountryData("ZZ")
            {
                DisplayName = "Unknown",
                ISO = 999,
                ISO2 = "ZZ",
                ISO3 = "ZZZ"
            };

            // Including Kosovo, that is till disputed: https://en.wikipedia.org/wiki/XK_(user_assigned_code)
            var data = new Dictionary<string, CountryData>()
            { 
                ["XK"] = new CountryData("XK")
                {
                    DisplayName = "Kosovo",
                    ISO2 = "XK",
                    ISO3 = "XKK",
                    StartDate = new(2008, 02, 01),
                }
            };

            foreach (var former in Iso3166_3s)
            {
                data[former.Name] = new(former.Name)
                {
                    DisplayName = former.DisplayName,
                    ISO = former.Iso,
                    ISO2 = former.Iso2,
                    ISO3 = former.Iso3,
                    StartDate = new(former.Start, 01, 01),
                    EndDate = new(former.End - 1, 12, 31),
                };
            }

            foreach(var c in Iso3166_1s)
            {
                data[c.A2] = new(c.A2)
                {
                    DisplayName = c.DisplayName,
                    ISO = c.NC,
                    ISO2 = c.A2,
                    ISO3 = c.A3,
                };
            }

            foreach (var c in Country.All)
            {
                var dat = data[c.Name];
                var updated = dat with
                {
                    StartDate = c.StartDate,
                    EndDate = c.EndDate,
                    CallingCode = c.CallingCode,
                };
                data[c.Name] = updated;
            }

            var resource = new XResourceFile();

            resource.Add("All", string.Join(';', data.Keys.OrderBy(c => c.Length).ThenBy(c => c)));
            resource.AddRange(unknown.Data());

            foreach (var info in data.Values.OrderBy(c => c.Name.Length).ThenBy(c => c.Name))
            {
                resource.AddRange(info.Data());
            }

            resource.Invoking(r => r.Save(Solution.Root.File("src/Qowaiv/Globalization/CountryLabels.resx")))
                .Should().NotThrow();
        }

        [Test]
        public async Task de_culture()
        {
            var resource = new XResourceFile(new XResourceFileData("ZZ_DisplayName", "Unbekannt", "Unknown (ZZ)"));

            foreach (var country in Country.All.OrderBy(c => c.Name.Length).ThenBy(c => c.Name))
            {
                var name = $"{country.Name}_DisplayName";
                var comment = $"{country.EnglishName} ({country.IsoAlpha2Code})";
                var value = country.Name.Length == 2 && await Display(country) is { } display
                    ? display
                    : country.GetDisplayName(TestCultures.De_DE);

                if (value != country.EnglishName)
                {
                    resource.Add(name, value, comment);
                }
            }

            resource.Invoking(r => r.Save(Solution.Root.File("src/Qowaiv/Globalization/CountryLabels.de.resx")))
                .Should().NotThrow();

            async Task<string?> Display(Country country)
            {
                try
                {
                    var lemma = new WikiLemma($"Vorlage:{country.IsoAlpha3Code}", TestCultures.De);
                    return await lemma.Transform(DisplayName.FromDE);
                }
                catch (UnknownLemma)
                {
                    return null;
                }
            }
        }

        [Test]
        public async Task nl_culture()
        {
            var resource = new XResourceFile(CountryDisplayName.Data("Onbekend", Country.Unknown));

            foreach (var country in Country.All)
            {
                var displayName = country.Name.Length == 2 && await Display(country) is { } display
                    ? display
                    : country.GetDisplayName(TestCultures.Nl_NL);

                if (displayName != country.EnglishName)
                {
                    resource.Add(CountryDisplayName.Data(displayName, country));
                }
            }

            resource.Invoking(r => r.Save(Solution.Root.File("src/Qowaiv/Globalization/CountryLabels.nl.resx")))
                .Should().NotThrow();

            async Task<string?> Display(Country country)
            {
                try
                {
                    var lemma = new WikiLemma($"Sjabloon:{country.Name}", TestCultures.Nl);
                    return await lemma.Transform(DisplayName.FromNL);
                }
                catch (UnknownLemma)
                {
                    return null;
                }
            }
        }
    }
}

public sealed record Iso3166_1(string DisplayName, string A2, string A3, int NC)
{
    public override string ToString() => $"{A2}/{A3}: {DisplayName} ({NC:000})";

    // Overrides of Wikipedia: 
    private static readonly Dictionary<string, string> Shorten = new()
    {
        ["Bolivia (Plurinational State of)"] = "Bolivia",
        ["Bonaire, Sint Eustatius and Saba"] = "Caribbean Netherlands",
        ["Iran (Islamic Republic of)"] = "Iran",
        ["Korea (Democratic People's Republic of)"] = "North Korea",
        ["Korea, Republic of"] = "South Korea",
        ["Lao People's Democratic Republic"] = "Laos",
        ["Micronesia (Federated States of)"] = "Micronesia",
        ["Moldova, Republic of"] = "Moldova",
        ["Netherlands, Kingdom of the"] = "Netherlands",
        ["Palestine, State of"] = "Palestine",
        ["Russian Federation"] = "Russia",
        ["<!--DO NOT CHANGE-->Taiwan, Province of China<!--This is the name used in ISO 3166: https://www.iso.org/obp/ui/#iso:code:3166:TW. If you disagree with this naming, contact the ISO 3166/MA; we must follow the published standard for this article.-->"] = "Taiwan",
        ["Tanzania, United Republic of"] = "Tanzania",
        ["United Kingdom of Great Britain and Northern Ireland"] = "United Kingdom",
        ["United States of America"] = "United States",
        ["Venezuela (Bolivarian Republic of)"] = "Venezuela",
        ["<!--DO NOT CHANGE-->{{not a typo|Sao Tome and Principe}}<!-- Do not change this to \"São Tomé and Príncipe\" unless https://www.iso.org/obp/ui/#iso:code:3166:ST changes to that spelling. If you disagree with the lack of diacritics, contact the ISO 3166/MA; we must follow the published standard for this article. -->"] = "Sao Tome and Principe",
    };

    public static IEnumerable<Iso3166_1> Parse(string str)
    {
        foreach (var line in str.Split("{{flagdeco|").Skip(1))
        {
            var parts = line.Split("mono|");

            if (parts.Length >= 4)
            {
                var link = WikiLink.Parse(parts[0]).First();
                var name = Wiki.RemoveInParentheses(link.Display);

                var a2 = parts[1][..2];
                var a3 = parts[2][..3];
                var nc = parts[3][..3];

                name = Shorten.TryGetValue(name, out var shorten) ? shorten : name;

                yield return new(name, a2, a3, int.Parse(nc));
            }
        }
    }
}

public sealed record Iso3166_3(string DisplayName, string Iso2, string Iso3, int Iso, int Start, int End, string Name)
{
    public override string ToString() => $"{Name}/{Iso2}: {DisplayName} ({Start}-{End})";

    public static IEnumerable<Iso3166_3> Parse(string str)
    {
        var entries = str.Split("|- ");
        
        foreach(var entry in entries.Skip(1))
        {
            var name = entry.Substring(entry.IndexOf(@"id=""") + 4, 4);

            if (name.Any(c => c < 'A' || c > 'Z')) continue;

            var display = WikiLink.Parse(entry).First().Display;

            var isos = entry.Split("mono|");
            var iso2 = isos[1][..2];
            var iso3 = isos[2][..3];
            var iso = int.TryParse(isos[3][..3], out var n) ? n : 0;

            var years = Regex.Match(entry, "(?<start>[0-9]{4}).(?<end>[0-9]{4})");
            var start = int.Parse(years.Groups["start"].Value);
            var end = int.Parse(years.Groups["end"].Value) - 1;

            yield return new(display, iso2, iso3, iso, start, end, name);
        }
    }
}

internal static class DisplayName
{
    private const string DE_prefix = "{{{3|";

    public static string? FromDE(string str)
    {
        var index = str.LastIndexOf(DE_prefix);
        if (index > -1)
        {
            var text = str[(index+DE_prefix.Length)..];
            return text[..text.IndexOf('}')];
        }
        else return null;
    }

    public static string? FromNL(string str)
    {
        var index = str.LastIndexOf("-VLAG}}&nbsp;") + 1;
        var text = str[index..];

        if (WikiLink.Parse(text).FirstOrDefault() is { } link)
        {
            var display = link.Display;
            display = display[(display.IndexOf('|') + 1)..];
            display = display.Trim('{').Trim('}');
            return display;
        }
        else return null;
    }
}

#endif
#endif
