// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("2.0.0.149")]
[assembly: AssemblyFileVersionAttribute("2.0.0.149")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0.149";
    }
}
