// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>To mark a method explicitly as impure. Methods decorated with
    /// this attribute return info about (like, removal or addition was successful).
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class CollectionMutationAttribute : global::Qowaiv.Diagnostics.Contracts.ImpureAttribute
    {
        public CollectionMutationAttribute(global::System.String? justification = null) : base(justification) { }
    }
}
