// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates the class is empty by design.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Interface, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal class EmptyInterfaceAttribute : global::Qowaiv.Diagnostics.Contracts.EmptyTypeAttribute
    {
        public EmptyInterfaceAttribute(global::System.String justification) : base(justification) { }
    }
}
