// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates the enum is empty by design.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Enum, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    internal sealed class EmptyTestEnumAttribute(global::System.String? justification) : global::Qowaiv.Diagnostics.Contracts.EmptyEnumAttribute(justification ?? "For test purposes.")
    {
        public EmptyTestEnumAttribute() : this(null) { }
    }
}
