// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates the class is empty by design.</summary>
    /// <remarks>
    /// Using this attribute prevents S2094 (Classes should not be empty) from
    /// showing up.
    /// </remarks>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    internal sealed class EmptyTestClassAttribute(global::System.String? justification) : global::Qowaiv.Diagnostics.Contracts.EmptyClassAttribute(justification ?? "For test purposes.")
    {
        public EmptyTestClassAttribute() : this(null) { }
    }
}
