// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>To mark a method explicitly as impure. Methods decorated with
    /// this attribute return the same instance that was provided as argument.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class FluentSyntaxAttribute(global::System.String? justification) : global::Qowaiv.Diagnostics.Contracts.ImpureAttribute(justification)
    {
        public FluentSyntaxAttribute() : this(null) { }
    }
}
