// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>To mark a method explicitly as impure.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    internal class ImpureAttribute(global::System.String? justification) : global::System.Attribute
    {
        public ImpureAttribute() : this(null) { }

        /// <summary>The justification of this decoration.</summary>
        public global::System.String? Justification { get; init; } = justification;
    }
}
