// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates the class is designed to be mutable.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct | global::System.AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal sealed class MutableAttribute(global::System.String? justification) : global::System.Attribute
    {
        public MutableAttribute() : this(null) { }

        /// <summary>The justification of this decoration.</summary>
        public global::System.String? Justification { get; init; } = justification;
    }
}
