// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates that the property/field is required to have a primitive type.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Property|global::System.AttributeTargets.Field, AllowMultiple = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal class PrimitiveRequiredAttribute : global::Qowaiv.Diagnostics.Contracts.EmptyTypeAttribute
    {
        public PrimitiveRequiredAttribute(global::System.String justification) : base(justification) { }
    }
}
