// <auto-generated/>
#pragma warning disable
#nullable enable

namespace Qowaiv.Diagnostics.Contracts
{
    /// <summary>Indicates the class will be sealed with the next major change.</summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Method | global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    [global::System.Diagnostics.Conditional("CONTRACTS_FULL")]
    internal sealed class WillBeSealedAttribute(global::System.String? justification) : global::Qowaiv.Diagnostics.Contracts.InheritableAttribute(justification)
    {
        public WillBeSealedAttribute() : this(null) { }
    }
}
