// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     - Qowaiv.CodeGeneration                    0.0.1-alpha-016
//     - Qowaiv.CodeGeneration.SingleValueObjects 1.0.0
//     - Qowaiv.CodeGeneration.Specs              1.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#if NET5_0_OR_GREATER

namespace Qowaiv.Json;

/// <summary>Provides a JSON conversion for a region.</summary>
public sealed class RegionJsonConverter : SvoJsonConverter<Region>
{
    /// <inheritdoc />
    [Pure]
    protected override Region FromJson(string? json) => Region.FromJson(json);

    /// <inheritdoc />
    [Pure]
    protected override Region FromJson(long json) => Region.FromJson(json);

    /// <inheritdoc />
    [Pure]
    protected override Region FromJson(double json) => Region.FromJson(json);

    /// <inheritdoc />
    [Pure]
    protected override Region FromJson(bool json) => Region.FromJson(json);

    /// <inheritdoc />
    [Pure]
    protected override object? ToJson(Region svo) => svo.ToJson();
}

#endif