using Qowaiv.CodeGeneration.Syntax;

namespace Qowaiv.CodeGeneration.SingleValueObjects;

public sealed class IdTemplate(IdParameters parameters) : Code
{
    private static readonly CodeSnippet Snippet
        = Embedded.Snippet("Behavior.Structure")
        + Embedded.Snippet("IEmpty")
        + Embedded.Snippet("Behavior.IComparable")
        + Embedded.Snippet("IEquatable")
        + Embedded.Snippet("Behavior.IFormattable")
        + Embedded.Snippet("Behavior.Json")
        + Embedded.Snippet("Behavior.IXmlSerializable")
        + Embedded.Snippet("Behavior.Id.Next")
        + Embedded.Snippet("Behavior.IParsable")
        + Embedded.Snippet("Behavior.Create");

    private readonly IdParameters Parameters = parameters;

    /// <inheritdoc />
    public void WriteTo(CSharpWriter writer) => Guard.NotNull(writer)
        .Write(Headers.AutoGenerated())
        .Write(Headers.EnableNullability)
        .Write(Headers.DisableWarnings)
        .Write(Snippet
            .Transform(line => line
                .Replace("@Svo", Parameters.Svo)
                .Replace("@Behavior", Parameters.Behavior)
                .Replace("@Value", Parameters.Value)
                .Replace("@Namespace", Parameters.Namespace.ToString())));

    /// <inheritdoc />
    [Pure]
    public override string ToString() => this.Stringify();
}
