name: 'Test Report'
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Unit test results
          path: '**/*.trx'
          reporter: dotnet-trx
